# Stage 1: Build
FROM golang:1.19 as build
WORKDIR /app
COPY . .
RUN go mod init app && go build -o app

# Stage 2: Production
FROM alpine:latest
WORKDIR /app
COPY --from=build /app/app .
CMD ["./app"]
